# Generated by Django 2.2.14 on 2020-10-26 15:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PackageSigningCert',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('signing_cert_CN', models.TextField()),
                ('signing_cert_sha256', models.CharField(max_length=64)),
                ('der_cert', models.BinaryField(blank=True, null=True)),
            ],
            options={
                'permissions': [('sign_appelflap_p2p_packages', 'Can sign Appelflap packages for P2P distribution')],
            },
        ),
    ]
